### ISSUE TITLE
Can I change to oracle database?

### ISSUE THREAD

**Issue by thanhctES** [miyabayt/spring-boot-doma2-sample#13]
This is great doma2 sample but Could you please tell me.
Can I switch to oracle database in this sample? and How to do that? Please advise me.

**Comment by Thirosue** [comment]
@thanhctES 

use oracle sample push feature/oracle branch.

https://github.com/miyabayt/spring-boot-doma2-sample/tree/feature/oracle

please see branch.

https://github.com/miyabayt/spring-boot-doma2-sample/commit/d510ed06035c3ab5c49cc451f04bc7dc77e235c0

**Comment by thanhctES** [comment]
Appreciate all and perfect for seeding.
