### ISSUE TITLE
 MySQLのUTF8問題（寿司ビール問題）に対応する

### ISSUE THREAD

**Issue by orinbou** [miyabayt/spring-boot-doma2-sample#30]
MySQLの文字コードutf8は、1~3バイトの文字しか格納できないので、絵文字や「𩸽」などの4バイト文字をDBへ格納することができない。

#### 参考URL
https://flhouse.co.jp/article/2/utf8mb4

**Comment by miyabayt** [comment]
マージしたのでクローズします。
